version: "3.8"
networks:
  redis-net:
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - redis-net
  rki-api:
    image: marlon360/rki-covid-server:v2
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDISHOST=redis
    networks:
      - redis-net
  covidinfo-de-server:
    environment:
      - NODE_ENV=development
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/app
    container_name: covidinfo-de-server
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run dev